// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, gender, status, id_department, id_town, direction, create_at, id_clinic, rol FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Gender,
		&i.Status,
		&i.IDDepartment,
		&i.IDTown,
		&i.Direction,
		&i.CreateAt,
		&i.IDClinic,
		&i.Rol,
	)
	return i, err
}
